In [1]:
#INSTALAR LIBRERIAS
%pip install pandas
%pip install numpy
%pip install matplotlib
%pip install seaborn
%pip install openpyxl

Requirement already satisfied: pandas in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (2.3.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.3.2)
Requirement already satisfied: packaging>=20.0 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: pandas>=1.2 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: openpyxl in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Convertir en dataframe
df= pd.read_csv("Datos_Facturación.csv")
df

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10890,10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaN,3272.00,0.0,0.0
10891,10891,F40307,6218.0,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,504.15,0.0,0.0
10892,10892,NaN,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,275.68,0.0,0.0
10893,10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaN,129.30,0.0,0.0
10894,10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaN,517.20,0.0,0.0

APLICACIÓN DE FILTROS

In [4]:
#1   CVE_CLPV valores 1,000 a 2,000
df_CLPV= df[(df['CVE_CLPV'] >= 1000) & (df['CVE_CLPV'] <= 2000)]
df_CLPV

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
18,18,F29432,1965.0,C,2.0,2019-09-05 11:05:04.000,2019-09-05,2019-09-05 00:00:00,2019-09-20,2019-09-06,976.50,0.00,0.0
22,22,F29436,1965.0,C,2.0,2019-09-06 12:01:36.000,2019-09-06,2019-09-06 00:00:00,2019-09-21,2019-09-12,976.50,0.00,0.0
65,65,F29479,1240.0,E,2.0,2019-09-11 18:38:45.000,2019-09-11,2019-09-11 00:00:00,2019-09-11,NaN,4135.00,0.00,0.0
71,71,F29485,1965.0,C,2.0,2019-09-12 12:14:28.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,2019-09-12,976.50,146.48,0.0
72,72,F29486,1965.0,E,2.0,2019-09-12 12:25:52.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,NaN,976.50,146.48,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10821,10821,F40237,1757.0,E,2.0,2023-02-24 15:18:17.570,2023-02-24,2023-02-13 00:00:00,2023-02-24,NaN,10088.40,0.00,0.0
10839,10839,F40255,1583.0,E,2.0,2023-02-28 09:15:45.753,2023-02-28,2023-02-28 00:00:00,2023-03-30,NaN,3467.35,0.00,0.0
10845,10845,F40261,1786.0,E,2.0,2023-02-28 11:15:32.527,2023-02-28,2023-03-03 00:00:00,2023-02-28,NaN,4663.80,0.00,0.0
10871,10871,F40287,1453.0,E,1.0,2023-03-01 12:58:23.397,2023-03-01,2023-02-27 00:00:00,2023-03-31,NaN,9000.00,0.00,0.0
10876,10876,F40292,1082.0,E,6.0,2023-03-02 11:00:54.770,2023-03-02,2023-03-01 00:00:00,2023-03-02,NaN,3262.00,0.00,0.0

In [5]:
#Exportar filtro df_CLPV a CSV
df_CLPV.to_csv("Filtro1.csv")

In [25]:
#Comprobamos que los valores de CVE_CLPV están entre 1,000 y 2,000
max(df_CLPV["CVE_CLPV"])
min(df_CLPV["CVE_CLPV"])

1016.0

In [ ]:
#2   CVE_VEND todas las claves excepto "5" y "4"
df_VEND= df[~df['CVE_VEND'].isin(['5', '4'])]
df_VEND

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10890,10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaN,3272.00,0.0,0.0
10891,10891,F40307,6218.0,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,504.15,0.0,0.0
10892,10892,NaN,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,275.68,0.0,0.0
10893,10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaN,129.30,0.0,0.0
10894,10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaN,517.20,0.0,0.0

In [8]:
#Exportar filtro df_VEND a CSV
df_VEND.to_csv("Filtro2.csv")

In [9]:
#3   FEHCA_ENT fechas de "28/02/2022"
df_FECHA= df[(df['FECHA_ENT'] == '2022-02-28 00:00:00')]
df_FECHA

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
8077,8077,F37493,4598.0,E,1.0,2022-02-28 10:56:02.460,2022-02-28,2022-02-28 00:00:00,2022-03-30,NaN,44259.0000,0.0,0.0
8078,8078,F37494,1943.0,C,2.0,2022-02-28 11:34:00.367,2022-02-28,2022-02-28 00:00:00,2022-02-28,2022-02-28,89.6800,0.0,0.0
8081,8081,F37497,1943.0,C,2.0,2022-02-28 12:05:42.377,2022-02-28,2022-02-28 00:00:00,2022-02-28,2022-02-28,89.6800,0.0,0.0
8083,8083,F37499,8573.0,E,2.0,2022-02-28 12:25:29.833,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,997.5400,0.0,0.0
8084,8084,F37500,8249.0,E,2.0,2022-02-28 12:32:46.687,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,2508.7000,0.0,0.0
8090,8090,F37506,1757.0,E,2.0,2022-02-28 13:23:45.440,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,2586.2100,0.0,0.0
8091,8091,F37507,3108.0,E,2.0,2022-02-28 13:52:43.383,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,675.4000,0.0,0.0
8092,8092,F37508,6232.0,E,2.0,2022-02-28 14:46:56.940,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,941.3965,0.0,0.0
8095,8095,F37511,8593.0,E,2.0,2022-02-28 15:20:58.040,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,218.9700,0.0,0.0
8096,8096,F37512,4766.0,E,2.0,2022-02-28 15:54:16.277,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,9450.0000,0.0,0.0
8100,8100,F37516,6179.0,E,3.0,2022-02-28 16:33:54.413,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,5951.7000,0.0,0.0
8103,8103,F37519,5150.0,E,3.0,2022-02-28 17:09:39.213,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,2040.0000,0.0,0.0
8104,8104,F37520,4527.0,E,2.0,2022-02-28 17:14:57.487,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,4315.0000,0.0,0.0
8107,8107,F37523,5926.0,E,2.0,2022-02-28 17:36:54.363,2022-02-28,2022-02-28 00:00:00,2022-02-28,NaN,451.6100,0.0,0.0
8133,8133,F37549,3016.0,E,1.0,2022-03-04 15:08:49.747,2022-03-04,2022-02-28 00:00:00,2022-03-04,NaN,1083.7200,0.0,0.0
8148,8148,F37564,4695.0,E,1.0,2022-03-08 09:15:20.507,2022-03-08,2022-02-28 00:00:00,2022-05-07,NaN,5515.0000,0.0,0.0
8204,8204,F37620,8316.0,E,3.0,2022-03-14 17:00:43.247,2022-03-14,2022-02-28 00:00:00,2022-03-14,NaN,24570.3000,0.0,0.0

In [10]:
#Exportar filtro df_FECHA a CSV
df_FECHA.to_csv("Filtro3.csv")

In [11]:
#4   CAN_TOT cantidades menores a 5,951.7 o STATUS "E"
df_CAN= df[(df['CAN_TOT'] < 5951.7) | (df['STATUS'] == 'E')]
df_CAN

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0.0
1,1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
2,2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0.0
3,3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0.0
4,4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10890,10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaN,3272.00,0.0,0.0
10891,10891,F40307,6218.0,NaN,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,504.15,0.0,0.0
10892,10892,NaN,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaN,275.68,0.0,0.0
10893,10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaN,129.30,0.0,0.0
10894,10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaN,517.20,0.0,0.0

In [12]:
#Exportar filtro df_CAN a CSV
df_CAN.to_csv("Filtro4.csv")

In [13]:
#5   Solo las columnas: CVE_DOC, FECHA_ENT, FEHCA_VEN, CANT_TOT
df_CV= df[['CVE_DOC', 'FECHA_ENT', 'FECHA_VEN', 'CAN_TOT']]
df_CV

      CVE_DOC            FECHA_ENT   FECHA_VEN  CAN_TOT
0      F29414  2019-09-03 00:00:00  2019-09-18  3980.00
1      F29415  2019-09-03 00:00:00  2019-10-03  1550.00
2      F29416  2019-09-03 00:00:00  2019-10-03  1550.00
3      F29417  2019-09-03 00:00:00  2019-10-03  1550.00
4      F29418  2019-09-03 00:00:00  2019-09-03  2435.44
...       ...                  ...         ...      ...
10890  F40306  2023-03-01 00:00:00  2023-03-06  3272.00
10891  F40307  2023-03-06 00:00:00  2023-03-06   504.15
10892     NaN  2023-03-06 00:00:00  2023-03-06   275.68
10893  F40309  2023-03-07 00:00:00  2023-03-07   129.30
10894  F40310  2023-03-01 00:00:00  2023-03-07   517.20

[10895 rows x 4 columns]

In [14]:
#Exportar filtro df_CV a CSV
df_CV.to_csv("Filtro5.csv")

In [15]:
#6   Solo las filas de 7001-7099
df_FILAS = df.loc[7001:7099, :]
df_FILAS

,Unnamed: 0,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
7001,7001,F36417,5271.0,E,3.0,2021-10-15 08:40:29.183,2021-10-15,2021-10-06 00:00:00,2021-11-14,NaN,8555.24,0.0,0.0
7002,7002,F36418,5746.0,E,2.0,2021-10-15 08:51:03.463,2021-10-15,2021-10-14 00:00:00,2021-10-15,NaN,620.77,0.0,0.0
7003,7003,F36419,2163.0,E,3.0,2021-10-15 08:56:23.280,2021-10-15,2021-10-15 00:00:00,2021-10-15,NaN,560.00,0.0,0.0
7004,7004,F36420,1429.0,E,1.0,2021-10-15 09:01:08.393,2021-10-15,2021-10-15 00:00:00,2021-12-14,NaN,23625.00,0.0,0.0
7005,7005,F36421,5039.0,E,1.0,2021-10-15 09:07:07.103,2021-10-15,2021-10-08 00:00:00,2022-01-13,NaN,3308.78,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7095,7095,F36511,4480.0,E,2.0,2021-10-27 13:07:43.223,2021-10-27,2021-10-27 00:00:00,2021-11-11,NaN,1137.50,0.0,0.0
7096,7096,F36512,8186.0,E,2.0,2021-10-27 13:22:23.980,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaN,94.84,0.0,0.0
7097,7097,F36513,4403.0,E,2.0,2021-10-27 13:35:40.677,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaN,847.00,0.0,0.0
7098,7098,F36514,5589.0,E,2.0,2021-10-27 14:02:54.630,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaN,965.00,0.0,0.0
7099,7099,F36515,5589.0,E,2.0,2021-10-27 14:04:26.797,2021-10-27,2021-10-26 00:00:00,2021-10-27,NaN,2106.00,0.0,0.0

In [16]:
#Exportar filtro df_FILAS a CSV
df_FILAS.to_csv("Filtro6.csv")

In [17]:
#7   Index= CVE_VEN (valores 1,2) (columna: FECHAELAB)
df_index = pd.read_csv("Datos_Facturación.csv", index_col=4)
df_index
df_VEN = df_index.loc[[1,2], ['FECHAELAB']]
df_VEN

                        FECHAELAB
CVE_VEND
1.0       2019-09-03 08:58:42.000
1.0       2019-09-03 09:55:14.000
1.0       2019-09-03 13:25:33.000
1.0       2019-09-03 13:33:23.000
1.0       2019-09-04 09:15:12.000
...                           ...
2.0       2023-03-06 16:09:39.013
2.0       2023-03-06 16:38:42.933
2.0       2023-03-06 17:02:33.390
2.0       2023-03-07 12:43:49.567
2.0       2023-03-07 12:45:58.407

[8665 rows x 1 columns]

In [ ]:
#Exportar filtro df_VEND a CSV
df_VEN.to_csv("Filtro7.csv")